### PR TITLE
Integration of shell

### PR DESCRIPTION
**Pull request by 9Mad-Max5**
implement an independent setting call aswell as an shell to start and stop the bot itself.

### CODE REVIEW

**Comment by An0nimia** [comment]
@9Mad-Max5 CTRL ^ C?

**Comment by 9Mad-Max5** [comment]
Yes I know you can stop in on this way.
But i wan´t a little script which is able to maybe restart it with cron or keep it alive with cron without starting mulitple instances.
If you don´t like it and wan´t pull it it´s ok for me.

**Comment by An0nimia** [comment]
@9Mad-Max5 I don't understand what do you mean with starting multiple instances

**Comment by 9Mad-Max5** [comment]
@An0nimia 
How do you start the bot usually on your machine. I try to use it on a pi like a 24/7 running bot which reacts on the messages. what is your use case?

**Comment by An0nimia** [comment]
@9Mad-Max5 ./name-script.py ?

**Pull request closed without merging**
