### PR TITLE
Added server_mode

### PR DESCRIPTION
**Pull request by 9Mad-Max5**
During using the server mode the files will not be deleted and not send as A audio.
If it is set to False there will be no difference in the usage of the Bot.

The shell is included for the same reason.

### CODE REVIEW

**Comment by 9Mad-Max5** [comment]
uff you don't like my pull?

**Comment by An0nimia** [comment]
@9Mad-Max5 Ah no that, I don't just want to modify my source code,  I like it how it is. =)

**Comment by 9Mad-Max5** [comment]
ok I fully understand that you like how it is but I think this could be a nice feature maybe there are more people using it similar like me?

**Comment by An0nimia** [comment]
@9Mad-Max5 So let them clone from your git

**Comment by 9Mad-Max5** [comment]
ok good point

**Pull request closed without merging**
